#!/usr/bin/env bash
# script that dispalys:
# "To infinity and beyond" indefinitely
# with a "sleep 2" in between each iteration
# "I am invincible!!!" when receiving a "SIGTERM" signal
counter=1;
while [ $counter -le 10 ]
do
	echo To infinity and beyond
	trap "echo I am invincible!!!" SIGTERM
	sleep 2
done
