#!/usr/bin/env bash
#script that displays numbers from 1 to 100
#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is a multiple of 3
#displays Buzz when the number is a multiple of 5
counter=1
while [ $counter -le 100 ]
do
	if [ $((counter % 3)) -eq 0 ] && [ $((counter % 5)) -eq 0 ]
	then
	    echo FizzBuzz
	elif [ $((counter % 5)) -eq 0 ]
	then
	    echo Buzz
	elif [ $((counter % 3)) -eq 0 ]
	then
	    echo Fizz
	else
	    echo $counter
	fi
	((counter++))
done
