#!/usr/bin/env bash
#Script that displays the time for 12hours and 59minutes
counter=0
y=1
while [ $counter -le 12 ]
do
    echo Hour: $counter
    while [ $y -le 59 ]
    do
	echo $y
	((y++))
    done
    y=1
    ((counter++))
done
